### ISSUE TITLE
[BUG] Default device memory allocation is too aggressive

### ISSUE THREAD

**Issue by JerryHOTS** [nv-legate/cupynumeric#1160]
### Software versions

```
Python      :  3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
Platform    :  Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
Legion      :  24.11.1 (commit: ac6aae07cb18fa9de978b073766dd9e3def29dbb)
Legate      :  24.11.1
[0 - 7f06e35b3600]    0.000000 {5}{module_config}: Module numa can not detect resources.
[0 - 7f06e35b3600]    0.000000 {4}{openmp}: numa support not found (or not working)
[0 - 7f06e35b3600]    0.000000 {5}{gpu}: /tmp/conda-croot/legate/work/arch-conda/skbuild_core/_deps/legion-src/runtime/realm/cuda/cuda_module.cc(3985):CUDA_DRIVER_FNPTR(cuIpcGetMemHandle)(&alloc.ipc_handle, alloc.dev_ptr) = 2(CUDA_ERROR_OUT_OF_MEMORY): out of memory
```

(Following's the output for nvidia-smi btw)

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.72                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8              1W /  120W |    7825MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      3830      C   /python3.12                                 N/A      |
+-----------------------------------------------------------------------------------------+
```

### Expected behavior

No error

### Observed behavior

When I run `legate-issue` or run `import cupynumeric as np` in python it raises the following error:

```
[0 - 7f06e35b3600]    0.000000 {5}{module_config}: Module numa can not detect resources.
[0 - 7f06e35b3600]    0.000000 {4}{openmp}: numa support not found (or not working)
[0 - 7f06e35b3600]    0.000000 {5}{gpu}: /tmp/conda-croot/legate/work/arch-conda/skbuild_core/_deps/legion-src/runtime/realm/cuda/cuda_module.cc(3985):CUDA_DRIVER_FNPTR(cuIpcGetMemHandle)(&alloc.ipc_handle, alloc.dev_ptr) = 2(CUDA_ERROR_OUT_OF_MEMORY): out of memory
```

### Example code or instructions

```
legate-issue
```

```
import cupynumeric as np
```

**Comment by manopapad** [comment]
Multiple issues here:

* Legate is attempting by default to reserve a large proportion of the device memory, and that's failing.
  * @JerryHOTS could you please try running with `LEGATE_SHOW_CONFIG=1`? The run will still fail, but we'll be able to see how much device memory Legate is attempting to reserve.
  * @JerryHOTS could you please try running with `LEGATE_CONFIG="--fbmem 1000"`? This will instruct Legate to try and reserve less memory.
  * @muraj looks like memory allocation is failing with `CUDA_ERROR_OUT_OF_MEMORY`, but in `cuIpcGetMemHandle`. Is it possible that there is, in fact, enough memory, but we're hitting a different system limit related to CUDA-IPC?
* Realm is complaining that we tried to instantiate NUMA-aligned memory, but that's not possible on the current system. This is not actually causing a failure in this case, but it is polluting the error message.
  * @eddy16112 is working on a Realm fix that would allow us to detect this issue before we put in our request for NUMA-aligned memory.
  * @JerryHOTS you can possibly make this go away by adding `--omps 0` to `LEGATE_CONFIG`.
* `legate-issue` is not working. This is an outcome of the fact that `legate-issue` is itself trying to import `cupynumeric`, so if the issue is with initialization itself, then `legate-issue` is going to hit it too.
  *  @bryevdv is looking into a fix.

**Comment by JerryHOTS** [comment]
Thank you very much for your prompt response! 

Running with `LEGATE_SHOW_CONFIG=1` gives: (terminal killed halfway)
Python      :  3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
Platform    :  Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
Legion      :  24.11.1 (commit: ac6aae07cb18fa9de978b073766dd9e3def29dbb)
Legate      :  24.11.1
Legate hardware configuration: --cpus=1 --gpus=1 --omps=1 --ompthreads=6 --utility=2 --sysmem=12677 --numamem=0 --fbmem=7778 --zcmem=128 --regmem=0
[0 - 7fc0c6d24600]    0.000000 {5}{module_config}: Module numa can not detect resources.
[0 - 7fc0c6d24600]    0.000000 {4}{openmp}: numa support not found (or not working)
[0 - 7fc0c6d24600]    0.000000 {5}{gpu}: /tmp/conda-croot/legate/work/arch-conda/skbuild_core/_deps/legion-src/runtime/realm/cuda/cuda_module.cc(3985):CUDA_DRIVER_FNPTR(cuIpcGetMemHandle)(&alloc.ipc_handle, alloc.dev_ptr) = 2(CUDA_ERROR_OUT_OF_MEMORY): out of memory

Running with `LEGATE_CONFIG="--fbmem 1000"` gives: (successful run)
Python      :  3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
Platform    :  Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
Legion      :  24.11.1 (commit: ac6aae07cb18fa9de978b073766dd9e3def29dbb)
Legate      :  24.11.1
[0 - 7f67147be600]    0.000000 {5}{module_config}: Module numa can not detect resources.
[0 - 7f67147be600]    0.000000 {4}{openmp}: numa support not found (or not working)
cuPynumeric :  24.11.02
Numpy       :  1.26.4
Scipy       :  1.14.1
Numba       :  (failed to detect)
CTK package :  cuda-version-12.6-h7480c83_3 (conda-forge)
GPU driver  :  566.14
GPU devices :  
  GPU 0: NVIDIA GeForce RTX 4070 Laptop GPU

And setting `--omps=0` doesn't solve the problem, with or without setting `"--fbmem 1000"`:
Python      :  3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
Platform    :  Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
Legion      :  24.11.1 (commit: ac6aae07cb18fa9de978b073766dd9e3def29dbb)
Legate      :  24.11.1
Legate hardware configuration: --cpus=1 --gpus=1 --omps=0 --ompthreads=0 --utility=2 --sysmem=12677 --numamem=0 --fbmem=7778 --zcmem=128 --regmem=0
[0 - 7fb3d0369600]    0.000000 {5}{module_config}: Module numa can not detect resources.
[0 - 7fb3d0369600]    0.000000 {5}{gpu}: /tmp/conda-croot/legate/work/arch-conda/skbuild_core/_deps/legion-src/runtime/realm/cuda/cuda_module.cc(3985):CUDA_DRIVER_FNPTR(cuIpcGetMemHandle)(&alloc.ipc_handle, alloc.dev_ptr) = 2(CUDA_ERROR_OUT_OF_MEMORY): out of memory

**Comment by manopapad** [comment]
OK, so it looks like indeed Legate's default device memory reservation was too aggressive. It tried reserving 7778MiB, based on the total memory size of 8188MiB. But based on your `nvidia-smi` output, it looks like only 7825MiB is actually available, i.e. quite close to what Legate requested (although it's not clear where the rest is going).

It's still curious that the error occurs at `cuIpcGetMemHandle` rather than `cuMemAlloc`.

There is an ongoing discussion about shifting our device memory allocation logic to happen dynamically through CUDA memory allocation calls, rather than allocating a pool in the beginning and allocating out of that. But there are multiple issues to work through, so it won't be available in the immediate term.

For now, I suggest you explicitly tell Legate how much memory to reserve, e.g. `LEGATE_CONFIG="--fbmem 7000"`, or whatever the maximum number is that works.

**Comment by JerryHOTS** [comment]
Thank you again for your help! When it's convenient, I would appreciate it if you could let me know when the fix becomes available.

**Comment by manopapad** [comment]
The full fix is getting delayed. For now we will query the currently available memory at startup (using `cuMemGetInfo`), and allocate 90-95% of that. This will work around the common scenario where another process (typically a graphics display server) is already using up some of the GPU device memory. Assuming the other memory use remains constant for the duration of the cuPyNumeric run, we should be able to co-exist with the prior user.

**Comment by eddy16112** [comment]
The fix has been merged https://github.com/nv-legate/legate.internal/pull/2166.

**Comment by manopapad** [comment]
It will take a few days for the fix to be propagated onto the nightly packages, need to make some updates to cuPyNumeric to align with latest Legate. I'll notify when that's done.

**Comment by manopapad** [comment]
@JerryHOTS as of 25.05.00.dev43 we should be taking current device memory into account at startup. Could you please confirm that this is working for you?

**Comment by manopapad** [comment]
@marcinz while we wait for @JerryHOTS to test the fix, I know you have had the same issue in the past, can you confirm the latest nightlies fix this for you?

**Comment by JerryHOTS** [comment]
Sorry for the delay, should be able to test it tomorrow

**Comment by manopapad** [comment]
@JerryHOTS could you please run with `LEGATE_AUTO_CONFIG=0`? It looks like only one core is being allocated to the Legate execution.

FYI @Jacobfaib it looks like the message with the actionable feedback might be getting lost inside the huge stacktrace in the error message. Should we perhaps print the exception string separately at the top of the message?

**Comment by JerryHOTS** [comment]
@manopapad It's now working ```
python -c "import cupynumeric as np; print(np.array([1, 2]) + np.array([3, 4]))"
[0 - 7fa8652e9600]    0.000000 {5}{module_config}: Module numa can not detect resources.
[0 - 7fa8652e9600]    0.000000 {4}{topology}: can't open /sys/devices/system/node/
[0 - 7fa8652e9600]    0.000249 {4}{threads}: reservation ('utility proc 1d00000000000001') cannot be satisfied
[4 6]
```

**Comment by Jacobfaib** [comment]
@manopapad Yes, it is a bit cluttered. I can see what can be done about demarcating the exception message from the stack trace.

**Comment by manopapad** [comment]
Thank you @JerryHOTS for confirming the fix. The warnings you see are relatively benign (they suggest that core pinning isn't happening, and that might have some performance implications).
